### ISSUE TITLE
The ffi-compiler on rubygems.org is too old

### ISSUE THREAD

**Issue by spacewander** [ffi/ffi-compiler#12]
The latest update time of `ffi-compiler` is April 19, 2013. This version is too old and without some added features.
https://rubygems.org/gems/ffi-compiler

**Comment by davispuh** [comment]
seems there still aren't any mainteiner for ffi-compiler :disappointed:  see ffi/ffi#339

@tduehr do you know what will happen with ffi-compiler? it's very useful and is used by many gems so new rubygem release is very needed.

**Comment by stakach** [comment]
Please cut a new release or feel free to make me an owner so I can push releases.
Really need `add_define` which was added to trunk in 2013 however is not available in any released gem.

Required to fix pbhogan/scrypt#58

**Comment by stakach** [comment]
@spacewander it took awhile however we have a new release v1.0.1
