### ISSUE TITLE
Is anyone interested in adding functionality/continuing support of ffi-compiler?

### ISSUE THREAD

**Issue by acaloiaro** [ffi/ffi-compiler#15]
Hi @stakach, 

I see you're the last person to commit to this project. I'm curious if you or anyone else has any desire to add functionality to this project. I ask because I'd like to add Golang support (https://github.com/ffi/ffi-compiler/pull/14). But if there's no appetite for such a change, I'm happy to add this functionality to my own fork and continue development there.

Cheers

**Comment by davispuh** [comment]
To me it looks unmaintained as years ago I had to publish `ffi-compiler2`, see #11

**Comment by acaloiaro** [comment]
👍 I'll open up a PR against `ffi-compiler2`.

**Comment by larskanis** [comment]
@davispuh Are you interested in maintaining ffi-compiler? You could merge you changes from ffi-compiler2 back and possibly merge the golang additions as well.

**Comment by davispuh** [comment]
I don't mind it, won't be first time I accidentally end up as maintainer :joy: Especially as looks like unfortunately no one else really cares but I use this gem in my projects just been a while.
