### ISSUE TITLE
Fix hompage and LICENSE?

### ISSUE THREAD

**Issue by utkarsh2102** [ffi/ffi-compiler#16]
Hi,

https://github.com/ffi/ffi-compiler/blob/daadf48781ed2cd4f1bad51d76fd8667de9dde82/ffi-compiler.gemspec#L8

This isn't valid, maybe needs an update?
Also, while at it, could you please add copyright holders (and years) to LICENSE?

**Comment by davispuh** [comment]
This is so trivial you could have submitted a PR yourself. Anyway submited #18
