### ISSUE TITLE
should ffi dependency be for 1.9.2+ because of license?

### ISSUE THREAD

**Issue by SergeyKanzhelev** [ffi/ffi-compiler#19]
`ffi` has changed license from LGPL to BSD at 1.9.2. Should this reference be updated to 1.9.2 to ensure that LGPL dependency will not be imported in any codebase using ffi-compiler:

https://github.com/ffi/ffi-compiler/blob/master/ffi-compiler.gemspec#L16

**Note: I have very limited context here and this suggestion comes from some confusion in license checks we ran. I don't think there is a real issue here.**

**Comment by davispuh** [comment]
Indeed. Now `ffi-compiler 1.3.1` have been released/published which depends on `ffi 1.15.5+`
