### ISSUE TITLE
Cannot install with bundler or with gem -P

### ISSUE THREAD

**Issue by ololobus** [ffi/ffi-compiler#20]
I'm trying to install another gem (https://github.com/abonas/kubeclient), which has a dependency on `ffi-compiler`. However, bundler says:
```
The gem ffi-compiler-1.0.1 can't be installed because the security policy didn't allow it, with the message: no digests provided (probable bug)
```

Actually, if I try install it with `gem install -P` (trust policy) it also fails:
```sh
$ gem install ffi-compiler -P MediumSecurity
Fetching ffi-compiler-1.0.1.gem
ERROR:  While executing gem ... (Gem::Security::Exception)
    no digests provided (probable bug)
```
and even with `NoSecurity`
```sh
$ gem install ffi-compiler -P NoSecurity 
WARNING:  email:steve (at) advancedcontrol.com.au is not trusted for ffi-compiler-1.0.1
ERROR:  While executing gem ... (Gem::Security::Exception)
    missing digest for metadata.gz
```

Probably `ffi-compiler` gem should be re-uploaded with a fresh certificate / digest.

Bundler version 2.2.15
ruby 3.0.1p64 (2021-04-05 revision 0fb782ee38) [x86_64-darwin20]
gem 3.2.15

**Comment by davispuh** [comment]
Yeah that certificate expired in 2017. I removed it and published `ffi-compiler 1.3.1`
