### ISSUE TITLE
Missing releases on rubygems.org

### ISSUE THREAD

**Issue by jirutka** [ffi/ffi-compiler#25]
The latest `ffi-compiler` release on [rubygems.org](https://rubygems.org/gems/ffi-compiler) is 1.0.1 from 2016, but the latest tagged version in this repository is [1.2.1](https://github.com/ffi/ffi-compiler/releases/tag/1.2.1).

@davispuh, can you please upload the missing releases to rubygems.org?

**Comment by davispuh** [comment]
I don't have keys to publish it there, maybe @stakach could?

**Comment by davispuh** [comment]
> Any update here? This breaks installing ffi gems locally on x86 on a recent update of the `llhttp-ffi` gem.

There can only be update when someone will find someone who has permissions to publish it.

Anyway in meanwhile you can use [ffi-compiler2](https://rubygems.org/gems/ffi-compiler2) - I just published updated version.

**Comment by davispuh** [comment]
Maybe @larskanis can?

**Comment by ixti** [comment]
I believe @enebo and @stakach are the current owners of the gem (on rubygems.org)

**Comment by enebo** [comment]
@davispuh Since you are the person committing the changes to ffi-compiler would you be ok releasing?  The fact you are already trusted to commit should give us trust you can also release (I can add you as someone who can push releases to rubygems.org).

**Comment by davispuh** [comment]
Yeah sure I don't mind. But maybe even better would be to setup "Trusted publisher + GitHub Action", see https://guides.rubygems.org/trusted-publishing/adding-a-publisher/ but I'm not really familiar with that.

Anyway this is my profile https://rubygems.org/profiles/davispuh (same ID on GMail aswell).

**Comment by enebo** [comment]
@davispuh That looks pretty nice.  I am not sure I have the time but I wish everything could just be publish on a particular action.  

I have added you as an owner (which you need to accept something -- don't recall that half of this).  Once confirmed if you can push the new gem we can look into setting up a publisher.

Thanks for stepping up.  You have already been doing the maintenance so you seem like a natural to be pushing the release.

**Comment by davispuh** [comment]
:partying_face: `ffi-compiler 1.3.1` have been released/published. https://rubygems.org/gems/ffi-compiler

I removed certificate since it expired in 2017 and I don't have key anyway. Also it doesn't seem worth bothering with signing gem.
